name: 'Close stale issues and PRs'

on:
  pull_request_target:
    types: [opened]

jobs:
  close-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Closes PRs older than 30 days
        id: close-prs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            let {data: pullRequests} = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (pr of pullRequests) {
              console.log(pr.created_at)

              let prDate = new Date(pr.created_at)
              let currentDate = new Date()

              let datesDiff = Math.abs(currentDate - prDate)
              // let daysDiff = Math.floor(datesDiff / (1000 * 60 * 60 * 24))
              let daysDiff = datesDiff

              console.log(daysDiff)

              if (daysDiff > 1) {
                console.log('should close PR')
              } else {
                console.log('no close')
              }
            }

