name: 'Close stale issues and PRs'

on:
  pull_request_target:
    types: [opened]

jobs:
  close-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Closes PRs older than 30 days
        id: close-prs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            let {data: pullRequests} = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            })

            for (pr of pullRequests) {
              if (pr.base.ref == 'main' && pr.head.ref == 'qa') {
                console.log('PR from QA to MAIN should not be closed')

                continue
              }

              console.log(`Checking age of PR on branch: ${pr.head.ref}`)

              let prDate = new Date(pr.created_at)
              let currentDate = new Date()

              let datesDiff = Math.abs(currentDate - prDate)
              // let daysDiff = Math.floor(datesDiff / (1000 * 60 * 60 * 24))
              let daysDiff = datesDiff

              console.log(daysDiff)

              if (daysDiff > 1) {
                await github.rest.pulls.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: pr.number,
                  state: 'closed'
                })
              }
            }

