name: 'Close stale issues and PRs'

on:
  pull_request_target:
    types: [opened]

jobs:
  close-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Closes PRs older than 30 days
        id: close-prs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            let {data: pr} = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })
            console.log(pr)
